import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import MobileNav from "../components/MobileNav";
import MobileHeader from "../components/MobileHeader";
import "./globals.css";

export const metadata = {
  title: "VedaAI Assessment Creator",
  description: "Generated by VedaAI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="app-container">
          <MobileHeader />
          <Sidebar />
          <div className="main-area">
            <Header />
            <div className="content-scroll">
              {children}
            </div>
          </div>
          
          <MobileNav />
        </div>
      </body>
    </html>
  );
}
